require 'editor'
require 'plugins'
require 'theme'

require 'config/astronauta'
require 'config/lsp'
require 'config/cmp'
require 'config/treesitter'
require 'config/telescope'
require 'config/null-ls'
require 'config/lspsaga'
require 'config/lsp_installer'
require 'config/cutlass'
require 'config/indentline'
require 'config/dashboard-nvim'
